name: ${pom.name}
main: me.youhavetrouble.particlewings.ParticleWings
authors: [YouHaveTrouble, Tigeax]
version: ${pom.version}
api-version: 1.21
softdepend:
  - Vault
  - TokenManager
permissions:
  particlewings.command:
    default: true
  particlewings.setwing:
    default: op
  particlewings.preview:
    default: op
  particlewings.editor:
    default: op
  particlewings.reload:
    default: op
  particlewings.takeawaywing:
    default: op
  particlewings.show:
    default: op
  particlewings.wing.*:
    default: op
  
